### ISSUE TITLE
Remove DNA from MyRobotLab - Refactor InMoov services with "attach" function and no DNA

### ISSUE THREAD

**Issue by supertick** [MyRobotLab/myrobotlab#101]
DNA & Peers was an attempt to "auto-configure" complex services.   But it proved problematic.  Now we are interested in using "attach" functions following our attach patterns

* http://myrobotlab.org/content/attach-pattern
* http://myrobotlab.org/content/service-attaching-diving-deeper
* http://myrobotlab.org/content/more-attach

The benefit of this, will be more clear "user" control of how the InMoov service is composed with other services & their configuration.  For example, it will be "easy" and clear to replace Arduinos with I2C Servo controllers by starting left & right I2C Servo controllers, configuring them and explicitly "attach"-ing them.

**Comment by kwatters** [comment]
Project Voltron!

**Comment by supertick** [comment]
I'll begin by creating an InMoov2 without peers

**Comment by supertick** [comment]
will not be doing this for Manticore release - dropping it from project board

**Comment by moz4r** [comment]
Is it the way to go ? https://github.com/MyRobotLab/pyrobotlab/blob/develop/service/InMoovEyelids.py

**Comment by MatsMRL** [comment]
No. I don't think so. You are still specifying that both eyelids are using
the same servoController
I would prefer the attach to be to each servoControl like this
public void attach(ServoControl leftEye, ServoControl rightEye)
That way you would be able to:
1. Have a different ServoController for each Servo
2. Use DiyServo instead of the Servo


2017-10-05 16:57 GMT+02:00 Anthony <notifications@github.com>:

**Comment by MatsMRL** [comment]
However, the idea of using attach instead of peers is good. So I think that
is the way to go.
As a rule of thumb.
1. Use interfaces.
2. Only attach one level away, not more.
Servo is one level and implements the ServoControl interface. ( Good to
attach to).
Arduino is two levels away and implements the ServoController interface, (
Avoid attaching to this level ).


2017-10-05 23:04 GMT+02:00 Mats Önnerby <mats.onnerby@gmail.com>:

**Comment by moz4r** [comment]
Ok, I understand now, there is is ServoControl **+** ServoController 
Is it correct ? ( two methods, 1 open, 1 easy for default things )

1/ `public void attach(ServoController controllerEyeLidLeft, ServoControl eyeLidLeft,Integer eyeLidLeftPin, ServoController controllerEyeLidRight, ServoControl eyeLidRight, Integer eyeLidRightPin)`

->>

`controllerEyeLidLeft = Runtime.start("controllerEyeLidLeft ","Adafruit16CServoDriver")`
`controllerEyeLidRight = Runtime.start("Arduino","Arduino")`
`eyeLidLeft = Runtime.start("eyeLidLeft ","DiyServo")`
`eyeLidRight = Runtime.start("eyeLidRight","Servo")`
`eyeLids.attach(controllerEyeLidLeft, eyeLidLeft, 2, controllerEyeLidRight, eyeLidRight, 4) `

2/ `public void attach(ServoController eyelidsController, eyeLidLeftPin, eyeLidRightPin)`

->>

`eyelidsController= Runtime.start("controllerEyeLidLeft ","Adafruit16CServoDriver")`
`eyeLids.attach(eyelidsController, 2, 4) `

**Comment by moz4r** [comment]
New Inmoov V2 in place ! It's a white page of code... 
Let attach things !

**Comment by moz4r** [comment]
Drafted InMoovHand2.
We can now use any supported servo & controllers, backward compatibility assured for existing gestures & standardized hardware configurations. If we are ok with this base method, need to extends others.

https://github.com/MyRobotLab/myrobotlab/blob/e39be622638537929a391648afbccef155b0960c/src/main/java/org/myrobotlab/service/InMoovHand2.java#L57

**Comment by supertick** [comment]
InMoov2 has been refactored to use pub/sub in combination with new configuration and peer defaults
much has changed
