### ISSUE TITLE
priorities on services shutdown

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/myrobotlab#220]
At runtime shutdown, services are calling stopService(). That is great.
I think it will be nice to get priorities on witch service is stopping before an other.
Example, every servo need to be released before arduino service.

**Comment by moz4r** [comment]
Hi ! you right I think to take care of attached services is necessary , 
What I want to do ( that is no worky perfect today ) is to rest() whole inmoov skeleton at runtime shutdown. For that I need servocontrol and servocontroller still alive, then they can release.

Solution is to rest() servo inside Servo serviceStop() but I'm not sure everyone want this. but that can be cleaner

**Comment by supertick** [comment]
Servo is low level - many things use it
InMoov is high level - it uses many things

Cleanest solution might be for InMoov to register for a shutdown event, so InMoov does the correct thing to shutdown - I would be careful of modifying servo, since many other services depend on it..

e.g. 
subscribe("runtime", "publishShutdown");
InMoov.onShutdown(int seconds) {
            log.info("shutting down InMoov in { } seconds", seconds);
            ... rest all servo services
            ... stop all servo services
            ... stop arduinos
           .... any other cleanup

**Comment by supertick** [comment]
all controlled by runtime config
easily changed or modified in a runtime.yml which is processed when you do a release on config
