### ISSUE TITLE
MRL install is broken

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/myrobotlab#317]
**Describe the bug**

Install "all" is broken ...

**To Reproduce**
Fresh folder, Install ( just ) opencv.
Then restart after opencv install
Then restart  and "Install all"

get this : `problem during retrieve of org.myrobotlab#myrobotlab-core: java.lang.RuntimeException: Multiple artifacts of the module org.bytedeco.javacpp-presets#ffmpeg;4.0.1-1.4.2 are retrieved to the same file! Update the retrieve pattern  to fix this error.`

**Desktop (please complete the following information):**
 - OS: win64

**Comment by supertick** [comment]
![noerror](https://user-images.githubusercontent.com/1266144/46873453-7c3a3c00-cdeb-11e8-9062-e5e2f23f2fb0.png)
Hmmm .. I followed instructions - but got this

**Comment by moz4r** [comment]
[myrobotlab.log](https://github.com/MyRobotLab/myrobotlab/files/2473356/myrobotlab.log)

**Comment by supertick** [comment]
Can't reproduce yet ... still trying :P

**Comment by wilcovantoorn** [comment]
I did full install and forgot to noworky but yes it did reproduce. I did click on the myrobotlab.jar file in Windows and it started. Did the install all and it ran until the same issue as TS.
I'm sorry I forgot to noworky.
Maybe because of the way I started, without java -jar and junk double clicked the jar file.

**Comment by supertick** [comment]
I have seen this too - but I'm not sure if its a mrl problem or an issue of catching the maven central or other transitive dependencies in flux.  It would be nice to freeze transitive version because I can still see maven going out to see if there are newer versions based on the descriptions of 1st level dependency transitives.
(next time someone sees it please re-open with more info) .. 

There was a multi-install fix done recently perhaps that fixed this problem too ?

**Comment by moz4r** [comment]
just tested the last, I still have the issue.
Looked at the pom, maybe a conflict between org.boofcv and TesseractOcr ? not sure ...

**Comment by kwatters** [comment]
I just tested here with the latest.  I installed opencv first. then I restarted, and did an install all.  there were no problems.
