### ISSUE TITLE
Latest api_refactor build does not start due to unrecognized command-line option "--spawned-from-agent"

### ISSUE THREAD

**Issue by AutonomicPerfectionist** [MyRobotLab/myrobotlab#549]
I have checked Runtime's CmdOptions and this option does in fact appear, and is listed when using --help, but upon crashing the help text does not list it. Manually executing Runtime.main() with --help does not list the option either.

**Comment by supertick** [comment]
fixed, and it is now in the --help

Usage: java -jar myrobotlab.jar  [-aBfhLuV] [--from-agent] [--interactive]
                                 [--spawned-from-agent] [--src[=<src>]] [-v
                                 [=<version>]] [-w[=<webgui>]] [--client
                                 [=<client>]]... [-b=<branch>] [-c=<cfg>]
                                 [--data-dir=<dataDir>] [-g=<agent>]
                                 [-l=<logLevel>] [-m=<memory>] [-n=<id>]
                                 [--proxy=<proxy>]
                                 [--resource-dir=<resourceDir>] [-j[=<jvm>...]]
                                 [-i[=<install>...]]... [-I[=<invoke>...]]...
                                 [-s[=<services>...]]... [-k=<addKeys>
                                 <addKeys>...]...
  -a, --auto-update          auto updating - this feature allows mrl instances
                               to be automatically updated when a new version
                               is available
  -b, --branch=<branch>      requested branch
  -B, --no-banner            prevents banner from showing
  -c, --cfg, --config=<cfg>  Configuration file. If specified all configuration
                               from the file will be used as a "base" of
                               configuration. All configuration of last run is
                               saved to {data-dir}/lastOptions.json. This file
                               can be used as a starter config for subsequent
                               --cfg config.json. If this value is set, all
                               other configuration flags are ignored.
      --client[=<client>]    starts a command line interface and optionally
                               connects to a remote instance - default with no
                               host param connects to agent process --client
                               [host]
      --data-dir=<dataDir>   sets the location of the data directory
  -f, --fork                 forks the agent, otherwise the agent will
                               terminate self if all processes terminate
      --from-agent           signals if the current process has been started by
                               an Agent
  -g, --agent=<agent>        command line options for the agent must be in
                               quotes e.g. --agent "--service pyadmin Python
                               --invoke pyadmin execFile myadminfile.py"
  -h, -?, --?, --help        shows help
  -i, --install[=<install>...]
                             installs all dependencies for all services,
                               --install {ServiceType} installs dependencies
                               for a specific service
  -I, --invoke[=<invoke>...] invokes a method on a service --invoke
                               {serviceName} {method} {param0} {param1} ... :
                               --invoke python execFile myFile.py
      --interactive          starts in interactive mode - reading from stdin
  -j, --jvm[=<jvm>...]       jvm parameters for the instance of mrl
  -k, --add-key=<addKeys> <addKeys>...
                             adds a key to the key store
                             @bold,italic java -jar myrobotlab.jar -k amazon.
                               polly.user.key ABCDEFGHIJKLM amazon.polly.user.
                               secret Fidj93e9d9fd88gsakjg9d93
  -l, --log-level=<logLevel> log level - helpful for troubleshooting  [debug
                               info warn error]
  -L, --list-versions        list all possible versions for this branch
  -m, --memory=<memory>      adjust memory can e.g. -m 2g
                              -m 128m
  -n, --id=<id>              process identifier to be mdns or network overlay
                               name for this instance - one is created at
                               random if not assigned
      --proxy=<proxy>        proxy config e.g. --proxy "http://webproxy:8080"
      --resource-dir=<resourceDir>
                             sets the location of the resource directory
  -s, --service, --services[=<services>...]
                             services requested on startup, the services must
                               be {name} {Type} paired, e.g. gui SwingGui
                               webgui WebGui servo Servo ...
      --spawned-from-agent   starts in interactive mode - reading from stdin
      --src, --use-source[=<src>]
                             use latest source
  -u, --update-agent         updates agent with the latest versions of the
                               current branch
  -v, --version[=<version>]  requested version or if left blank return version
  -V, --virtual              sets global environment as virtual - all services
                               which support virtual hardware will create
                               virtual hardware
  -w, --webgui[=<webgui>]    starts webgui for the agent - this starts a server
                               on port 127.0.0.1:8887 that accepts websockets
                               from spawned clients. --webgui {address}:{port}
