### ISSUE TITLE
Translator service migration

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/myrobotlab#74]
Microsoft had close the old api.
Service no worky anymore
need to migrate to azure

**Comment by hairygael** [comment]
Azure translator use to work on my scripts with Acapella.
Since we switched to Natural reader, it doesn't work, but you said it was
not related..?

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2017-05-10 12:03 GMT+02:00 Anthony <notifications@github.com>:

**Comment by moz4r** [comment]
correct it was bad coincidence. Microsoft had shutdown an authentication token. to use a new one ( azure platform ) . soon, it will be an old story ! every puzzle pieces ok
