### ISSUE TITLE
Check RasPI I2C caching device address issue

### ISSUE THREAD

**Issue by supertick** [MyRobotLab/myrobotlab#900]

**Comment by Cyber-One** [comment]
The issue is easy to replicate.
Connect one or more I2C devices to the Raspberry Pi and start MRL
Start the Raspi service and click on the scan I2C bus button
Once it has returned and is displaying the list of address, disconnect one of more of the devices.
Pressing the Scan I2C Bus will result with the same list of devices even though one or more are no longer connected.

**Comment by supertick** [comment]
fixed in PR #905
