### ISSUE TITLE
wikidata getdata quantity broken ?

### ISSUE THREAD

**Issue by moz4r** [MyRobotLab/myrobotlab#94]
what is the fruit of apple tree > ok ( fruit:P1672 )
what is the height of eiffel tower > nok

getData("eiffel tower","P2048");

**Comment by moz4r** [comment]
hi beetle, is it worky for you ?

**Comment by beetlejuiceFR** [comment]
Hi, No it stopped to work for me too ! I will try to fix it !

**Comment by moz4r** [comment]
Thank you ! Happy to "see" you ! I think it crash here : https://github.com/MyRobotLab/myrobotlab/blob/master/src/org/myrobotlab/service/WikiDataFetcher.java#L282

There is a wiki sdk 0.0.8 Snapshot but I didnt test it

**Comment by beetlejuiceFR** [comment]
I'm still trying to find the problem . I think more it's caused by the getSnak() function . Strangely it work fine for other queries . At this line https://github.com/MyRobotLab/myrobotlab/blob/master/src/org/myrobotlab/service/WikiDataFetcher.java#L241 , i add the value in an array that contain the dataType ( in A1(0) ) and the value ( in A1(1) ) . For a quantity, A1(1) is empty ! So getSnak found the page "Eiffeil Tower" and the property "P2048" but can't get the value for this property ....

**Comment by hairygael** [comment]
Just to mention but I'm sure you already know, through ProgramAB, I get the
correct answer regarding the heigth of the Eiffel Tower. But of course it
doesn't use DataFetcher, it searchs the net and get the answer on the
website Answers.com.

Gael Langevin
Creator of InMoov
InMoov Robot <http://www.inmoov.fr>
@inmoov <http://twitter.com/inmoov>



2017-07-12 11:52 GMT+02:00 beetlejuiceFR <notifications@github.com>:

**Comment by beetlejuiceFR** [comment]
Hi, sorry but i still didn't find the problem ! Perhaps, the version 0.8.0 of wikidata toolkit will repair this. I'm waiting this new release but i'm still trying to fix it ;)

@hairygael : thx . But you're right both services are different !

**Comment by supertick** [comment]
Hi, I'd like to help...  
Can we come up with a set of tests, which we can put into the auto-magical-tests we run every build ?  So that we can see if the service is worky or not worky ?

I'll start searching for example tests - my usual mode of working is to test in the main() function - then move those tests to a Junit class named WikiDataFetcherTest...   I'll start looking for some tests...

**Comment by moz4r** [comment]
Thanks , help is welcome !
I have set the main() with noworky sample 
That will break the build :) 

Datatype : quantity01:07:55.090 [main] ERROR class org.myrobotlab.logging.Logging - ------
java.lang.NullPointerException
	at org.wikidata.wdtk.datamodel.helpers.ToString.toString(ToString.java:186)
	at org.wikidata.wdtk.datamodel.json.jackson.datavalues.JacksonValueQuantity.toString(JacksonValueQuantity.java:122)
	at org.myrobotlab.service.WikiDataFetcher.getData(WikiDataFetcher.java:293)
	at org.myrobotlab.service.WikiDataFetcher.main(WikiDataFetcher.java:54)

**Comment by supertick** [comment]
Fixed.
I'm impressed - very cool service, I did not find much documentation on google regarding example client.  There were example clients, but what they did are not as clear as this service which beetle created.

So the problem was "units" was being retrieved by this
`String unit = data.toString();`

data is some json object .. the "weird" thing about this is it blows up when you do a .toString() - which usually does not happen in decent code - but somehow this is borked...
data.toString() is dangerous I guess in the wiki-data-client code :(

I did this,
`String unit = String.valueOf(((QuantityValue) data).getUnit());`
Worky
325 **metres** comes back

This is the javadoc with the clue 
http://wikidata.github.io/Wikidata-Toolkit/index.html?org/wikidata/wdtk/datamodel/interfaces/QuantityValue.html

There are other places where data.toString() is used, but I'll guess we'll fix them (when/if) they blow up.

Cheers !

**Comment by beetlejuiceFR** [comment]
Well done ! Thank you !

**Comment by moz4r** [comment]
nice !! thank you captain

**Comment by moz4r** [comment]
seem we need to update Wikidata-Toolkit to 0.0.8
https://github.com/Wikidata/Wikidata-Toolkit/issues/293

**Comment by moz4r** [comment]
Fixed & worky locally , pushed but build is broken because Jenkins issue ( need to refresh local git repo )

**Comment by moz4r** [comment]
worky !
